Add angular-build tool
gisaia/DockerUtils pull request #17
Opened 2019-05-28 19:34 UTC by sebbousquet

2019-05-29 02:45 UTC, MohamedHamouGisaia approved these changes

2019-05-29 09:07 UTC, elouanKeryell-Even requested changes

2019-05-29 09:07 UTC, elouanKeryell-Even commented on angular-build/README.md
> +    -v package.json:/package.json \
I think we should mount it in read-only mode, to guarantee the user we are not going to modify its `package.json`. That would be:

```bash
-v package.json:/package.json:ro
```

2019-05-29 09:07 UTC, elouanKeryell-Even commented on angular-build/README.md
> +    gisaia/angular-build:0.0.1
I see the container requires command-line arguments for `ng` option `--base-href`, yet in this example, no command-line argument is given to the container. I fail to see how this example would work :confused: .

2022-12-15 13:43 UTC, sebbousquet commented
Not relevant anymore

2022-12-15 13:43 UTC, closed without merging